import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const previousHome = process.env.MR_ROBOT_HOME;
const testHome = mkdtempSync(join(tmpdir(), 'mr-robot-discord-authority-'));
process.env.MR_ROBOT_HOME = testHome;
const { AgentServer } = await import('../src/server/server.js');
const { ChatSession } = await import('../src/server/chat.js');
const { ToolExecutor } = await import('../src/ai/executor.js');
const server = new AgentServer();
try {
  server.config.updateSettings({ safety: { ...server.config.settings.safety, mode: 'workspace' } });
  const grant = server.config.createDeviceLink('fixture', 'full', []);
  (server as any).discordLinkIds.add(grant.link.id);
  const local = (server as any).authenticateWebSocket(grant.token, undefined, true);
  const remote = (server as any).authenticateWebSocket(grant.token, undefined, false);
  assert.equal(local.trustedDiscord, true);
  assert.equal(local.isAdmin, false);
  assert.equal(remote.trustedDiscord, undefined);
  assert.equal(server.authenticate(grant.token)?.trustedDiscord, undefined, 'REST never grants Discord run override');
  const observed: any[] = [];
  server.loop.run = async (_history, _text, _callbacks, _tools, options) => { observed.push(options); return { text: 'fixture', turns: [], usage: { promptTokens: 0, completionTokens: 0 } }; };
  const handlers = (server as any).handlers();
  const client = (auth: any, id: string) => ({ id, state: { auth, chat: new ChatSession() } });
  await handlers.get('chat.start')({ text: 'fixture', permissionMode: 'full', tokenPolicy: 'audit-only', trustedPermissionOverride: true }, client(remote, 'remote'));
  await handlers.get('chat.start')({ text: 'fixture', permissionMode: 'full', tokenPolicy: 'audit-only' }, client(local, 'local'));
  assert.equal(observed[0].permissionMode, 'workspace', 'remote body cannot forge local authority');
  assert.equal(observed[0].trustedPermissionOverride, false);
  assert.equal(observed[1].permissionMode, 'full');
  assert.equal(observed[1].trustedPermissionOverride, true);
  await handlers.get('chat.start')({ text: 'isolated fixture', permissionMode: 'workspace', discordIsolation: 'isolated', tokenPolicy: 'audit-only' }, client(local, 'isolated'));
  assert.ok(observed[2].isolation);
  assert.equal(observed[2].workspacePath, undefined, 'isolated users must never inherit PC default workspace');
  assert.ok(!observed[2].context.includes('장기 기억'));
  await assert.rejects(observed[2].isolation.execute('read_file', { path: 'C:\\private.txt' }));
  let mode: 'workspace' | 'read-only' = 'workspace';
  let executed = 0;
  const executor = new ToolExecutor({ computer: {} as any, safety: () => ({ mode, maxReadBytes: 1024, maxShellBytes: 1024, allowedRoots: [] }), runPluginTool: async () => { executed++; return {}; } });
  await executor.execute('fixture.command', {}, undefined, 'full');
  assert.equal(executed, 0, 'ordinary full requests respect global workspace ceiling');
  await executor.execute('fixture.command', {}, undefined, 'full', undefined, { trustedPermissionOverride: true });
  assert.equal(executed, 1);
  mode = 'read-only';
  await executor.execute('fixture.command', {}, undefined, 'full', undefined, { trustedPermissionOverride: true });
  assert.equal(executed, 1, 'PC read-only emergency stop remains authoritative');
  server.config.revokeDeviceLink(grant.link.id);
  assert.equal((server as any).authenticateWebSocket(grant.token, undefined, true), null);
  console.log('Discord authority passed: local-only scope, no admin escalation, body forgery rejected, full tools, read-only kill switch, revocation');
} finally {
  await server.stop();
  if (previousHome === undefined) delete process.env.MR_ROBOT_HOME; else process.env.MR_ROBOT_HOME = previousHome;
  rmSync(testHome, { recursive: true, force: true });
}
