import assert from 'node:assert/strict';
import { DiscordSessions } from '../src/plugins/discord-sessions.js';
const data = new Map<string, any>();
const storage = { get: <T>(key: string) => data.has(key) ? structuredClone(data.get(key)) as T : undefined, set: (key: string, value: unknown) => { data.set(key, structuredClone(value)); } };
let registry = new DiscordSessions(storage);
const base = { guildId: '111111111111111111', channelId: '222222222222222222', userId: '333333333333333333', allowAi: true };
const threadId = '444444444444444444';
const run = (action: string, fields = {}, busy = '') => registry.command({ ...base, action, ...fields }, busy)?.result as any;
run('thread.bind');
for (const allowAi of [undefined, false, 'true', 1]) assert.throws(() => run('thread.register', { threadId, allowAi }), /allow_ai/);
assert.equal(run('thread.list').length, 0, 'missing role cannot allocate a session');
assert.throws(() => run('thread.bind', { channelId: threadId }), /이미/);
assert.throws(() => run('thread.register', { channelId: threadId, threadId: '555555555555555555' }), /연결/);
run('thread.register', { threadId, name: 'My session' });
const own = { ...base, channelId: threadId, isThread: true };
const foreign = { ...own, userId: '666666666666666666' };
assert.throws(() => registry.assertOwner({ ...foreign, action: 'ask' }), /본인/);
assert.throws(() => registry.assertOwner({ ...own, channelId: '777777777777777777', action: 'ask' }), /본인/);
assert.throws(() => run('thread.register', { threadId }), /이미/);
assert.throws(() => registry.command({ ...foreign, action: 'thread.forget' }, ''), /본인/);
assert.equal(run('thread.list', { userId: foreign.userId }).length, 0);
assert.equal(run('thread.list').length, 1);
registry = new DiscordSessions(storage);
assert.equal(run('thread.list')[0].name, 'My session', 'survives host restart');
assert.throws(() => run('thread.archive', { channelId: threadId }, registry.scope(own)), /중지/);
assert.throws(() => run('thread.unbind', {}, registry.scope(own)), /중지/);
run('thread.archive', { channelId: threadId });
assert.throws(() => registry.assertOwner({ ...own, action: 'ask' }), /보관/);
run('thread.reopen', { channelId: threadId });
registry.assertOwner({ ...own, action: 'ask' });
run('thread.unbind');
assert.throws(() => registry.assertOwner({ ...own, action: 'ask' }), /연결/);
assert.throws(() => run('thread.reopen', { channelId: threadId }), /부모/);
run('thread.bind');
const scope = registry.scope(own);
for (const key of ['permissions', 'conversations', 'preferences']) storage.set(key, { [scope]: 'fixture', unrelated: 'keep' });
run('thread.forget', { channelId: threadId });
assert.equal(run('thread.list').length, 0);
for (const key of ['permissions', 'conversations', 'preferences']) assert.deepEqual(storage.get(key), { unrelated: 'keep' });
assert.throws(() => registry.assertOwner({ ...own, action: 'ask' }), /本|본인/);
console.log('Discord sessions passed: binding, ownership, persistence, archive/reopen, busy guards, unbind, isolated cleanup');
